# Puerta de tu aplicación (Donde verás los datos en el navegador)
server.port=8081

# Conexión a la base de datos (PostgreSQL se queda en 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/reservairbnb_db
spring.datasource.username=postgres
spring.datasource.password=MARIANA20209
spring.jpa.hibernate.ddl-auto=update